version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=labuser
      - DB_PASS=labpass
      - DB_NAME=school_lab

  db:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: school_lab
      MYSQL_USER: labuser
      MYSQL_PASSWORD: labpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: labuser
      PMA_PASSWORD: labpass
    depends_on:
      - db

volumes:
  db_data:
